name: Semantic Versioning & Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Node.js for semantic-release
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install semantic-release dependencies
        run: npm install

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
